services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://mongo:27017/healthscan
      REDIS_URL: redis://redis:6379
      JWT_ACCESS_SECRET: dev-access-change-me
      JWT_REFRESH_SECRET: dev-refresh-change-me
      NODE_ENV: development
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data: {}
